Introduce CompositeUserRepository #196
Haulmont/jmix-core pull request #197
Opened 2021-06-18 13:20 UTC by glebshalyganov

2021-06-18 13:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Haulmont/jmix-core?pullRequest=197) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Haulmont/jmix-core?pullRequest=197) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Haulmont/jmix-core?pullRequest=197) it.</sub>

2021-06-23 06:58 UTC, andreysubbotin requested changes

2021-06-23 06:58 UTC, andreysubbotin commented on core/src/main/java/io/jmix/core/security/CompositeUserRepository.java
> +            } catch (Exception e) {
Perhaps it is worth catching a `UsernameNotFoundException`?

2021-06-23 06:58 UTC, andreysubbotin commented on core/src/main/java/io/jmix/core/security/CompositeUserRepository.java
> +                continue;
Log the error message

2021-06-23 06:58 UTC, andreysubbotin commented on core/src/main/java/io/jmix/core/security/CompositeUserRepository.java
> +                continue;
Log the error message

2021-06-23 07:21 UTC, closed without merging

2021-06-23 07:22 UTC, glebshalyganov commented
merged
https://github.com/Haulmont/jmix-core/commit/9627bdec9c115966a64f163cef02bf64d13ca40e
https://github.com/Haulmont/jmix-core/commit/4e74c686d499f122268a8321cc841b371f27efb9